server:
  port: 9191
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: otus.p12
    key-store-password: 123456
    key-alias: otus1
  servlet:
    context-path: /app
spring:
  datasource:
    url: jdbc:postgresql://localhost:8282/otus
    password: otus
    username: otus
  logging:
    level:
      org.springframework.jdbc.core.JdbcTemplate: TRACE